// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"parsing/orm/ent/page"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PageCreate is the builder for creating a Page entity.
type PageCreate struct {
	config
	mutation *PageMutation
	hooks    []Hook
}

// SetBrand sets the "brand" field.
func (pc *PageCreate) SetBrand(s string) *PageCreate {
	pc.mutation.SetBrand(s)
	return pc
}

// SetDomain sets the "domain" field.
func (pc *PageCreate) SetDomain(s string) *PageCreate {
	pc.mutation.SetDomain(s)
	return pc
}

// SetJob sets the "job" field.
func (pc *PageCreate) SetJob(s string) *PageCreate {
	pc.mutation.SetJob(s)
	return pc
}

// SetHTML sets the "html" field.
func (pc *PageCreate) SetHTML(s string) *PageCreate {
	pc.mutation.SetHTML(s)
	return pc
}

// SetCreated sets the "created" field.
func (pc *PageCreate) SetCreated(t time.Time) *PageCreate {
	pc.mutation.SetCreated(t)
	return pc
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (pc *PageCreate) SetNillableCreated(t *time.Time) *PageCreate {
	if t != nil {
		pc.SetCreated(*t)
	}
	return pc
}

// SetUpdated sets the "updated" field.
func (pc *PageCreate) SetUpdated(t time.Time) *PageCreate {
	pc.mutation.SetUpdated(t)
	return pc
}

// SetNillableUpdated sets the "updated" field if the given value is not nil.
func (pc *PageCreate) SetNillableUpdated(t *time.Time) *PageCreate {
	if t != nil {
		pc.SetUpdated(*t)
	}
	return pc
}

// SetProcessed sets the "processed" field.
func (pc *PageCreate) SetProcessed(t time.Time) *PageCreate {
	pc.mutation.SetProcessed(t)
	return pc
}

// SetNillableProcessed sets the "processed" field if the given value is not nil.
func (pc *PageCreate) SetNillableProcessed(t *time.Time) *PageCreate {
	if t != nil {
		pc.SetProcessed(*t)
	}
	return pc
}

// SetURL sets the "url" field.
func (pc *PageCreate) SetURL(s string) *PageCreate {
	pc.mutation.SetURL(s)
	return pc
}

// Mutation returns the PageMutation object of the builder.
func (pc *PageCreate) Mutation() *PageMutation {
	return pc.mutation
}

// Save creates the Page in the database.
func (pc *PageCreate) Save(ctx context.Context) (*Page, error) {
	pc.defaults()
	return withHooks(ctx, pc.sqlSave, pc.mutation, pc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PageCreate) SaveX(ctx context.Context) *Page {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *PageCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *PageCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pc *PageCreate) defaults() {
	if _, ok := pc.mutation.Created(); !ok {
		v := page.DefaultCreated()
		pc.mutation.SetCreated(v)
	}
	if _, ok := pc.mutation.Updated(); !ok {
		v := page.DefaultUpdated()
		pc.mutation.SetUpdated(v)
	}
	if _, ok := pc.mutation.Processed(); !ok {
		v := page.DefaultProcessed
		pc.mutation.SetProcessed(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *PageCreate) check() error {
	if _, ok := pc.mutation.Brand(); !ok {
		return &ValidationError{Name: "brand", err: errors.New(`ent: missing required field "Page.brand"`)}
	}
	if v, ok := pc.mutation.Brand(); ok {
		if err := page.BrandValidator(v); err != nil {
			return &ValidationError{Name: "brand", err: fmt.Errorf(`ent: validator failed for field "Page.brand": %w`, err)}
		}
	}
	if _, ok := pc.mutation.Domain(); !ok {
		return &ValidationError{Name: "domain", err: errors.New(`ent: missing required field "Page.domain"`)}
	}
	if v, ok := pc.mutation.Domain(); ok {
		if err := page.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "Page.domain": %w`, err)}
		}
	}
	if _, ok := pc.mutation.Job(); !ok {
		return &ValidationError{Name: "job", err: errors.New(`ent: missing required field "Page.job"`)}
	}
	if v, ok := pc.mutation.Job(); ok {
		if err := page.JobValidator(v); err != nil {
			return &ValidationError{Name: "job", err: fmt.Errorf(`ent: validator failed for field "Page.job": %w`, err)}
		}
	}
	if _, ok := pc.mutation.HTML(); !ok {
		return &ValidationError{Name: "html", err: errors.New(`ent: missing required field "Page.html"`)}
	}
	if v, ok := pc.mutation.HTML(); ok {
		if err := page.HTMLValidator(v); err != nil {
			return &ValidationError{Name: "html", err: fmt.Errorf(`ent: validator failed for field "Page.html": %w`, err)}
		}
	}
	if _, ok := pc.mutation.Created(); !ok {
		return &ValidationError{Name: "created", err: errors.New(`ent: missing required field "Page.created"`)}
	}
	if _, ok := pc.mutation.Updated(); !ok {
		return &ValidationError{Name: "updated", err: errors.New(`ent: missing required field "Page.updated"`)}
	}
	if _, ok := pc.mutation.Processed(); !ok {
		return &ValidationError{Name: "processed", err: errors.New(`ent: missing required field "Page.processed"`)}
	}
	if _, ok := pc.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Page.url"`)}
	}
	if v, ok := pc.mutation.URL(); ok {
		if err := page.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Page.url": %w`, err)}
		}
	}
	return nil
}

func (pc *PageCreate) sqlSave(ctx context.Context) (*Page, error) {
	if err := pc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	pc.mutation.id = &_node.ID
	pc.mutation.done = true
	return _node, nil
}

func (pc *PageCreate) createSpec() (*Page, *sqlgraph.CreateSpec) {
	var (
		_node = &Page{config: pc.config}
		_spec = sqlgraph.NewCreateSpec(page.Table, sqlgraph.NewFieldSpec(page.FieldID, field.TypeInt))
	)
	if value, ok := pc.mutation.Brand(); ok {
		_spec.SetField(page.FieldBrand, field.TypeString, value)
		_node.Brand = value
	}
	if value, ok := pc.mutation.Domain(); ok {
		_spec.SetField(page.FieldDomain, field.TypeString, value)
		_node.Domain = value
	}
	if value, ok := pc.mutation.Job(); ok {
		_spec.SetField(page.FieldJob, field.TypeString, value)
		_node.Job = value
	}
	if value, ok := pc.mutation.HTML(); ok {
		_spec.SetField(page.FieldHTML, field.TypeString, value)
		_node.HTML = value
	}
	if value, ok := pc.mutation.Created(); ok {
		_spec.SetField(page.FieldCreated, field.TypeTime, value)
		_node.Created = value
	}
	if value, ok := pc.mutation.Updated(); ok {
		_spec.SetField(page.FieldUpdated, field.TypeTime, value)
		_node.Updated = value
	}
	if value, ok := pc.mutation.Processed(); ok {
		_spec.SetField(page.FieldProcessed, field.TypeTime, value)
		_node.Processed = value
	}
	if value, ok := pc.mutation.URL(); ok {
		_spec.SetField(page.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	return _node, _spec
}

// PageCreateBulk is the builder for creating many Page entities in bulk.
type PageCreateBulk struct {
	config
	err      error
	builders []*PageCreate
}

// Save creates the Page entities in the database.
func (pcb *PageCreateBulk) Save(ctx context.Context) ([]*Page, error) {
	if pcb.err != nil {
		return nil, pcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Page, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *PageCreateBulk) SaveX(ctx context.Context) []*Page {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *PageCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *PageCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}
